### ISSUE TITLE
TASK [role_cloud : AWS configure] error when retry

### ISSUE THREAD

**Issue by qiaofeng1227** [websoft9dev/role_cloud#2]
TASK [role_cloud : AWS Configure] *************************************************************************
fatal: [54.209.215.247]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://repo.mysql.com/apt/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8C718D3B5072E1F5, E:The repository 'http://repo.mysql.com/apt/ubuntu focal InRelease' is not signed."}

**Comment by chendelin1982** [comment]
`sudo apt update` also have the same error for the reason of MySQL key fetch failed
Add this task for retry
```
- name: Delete MySQL mysql.list for retry
  shell: rm -rf /etc/apt/sources.list.d/mysql.list
```

**Comment by chendelin1982** [comment]
Done
